In [27]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from joblib import dump

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
import joblib

In [28]:
df = pd.read_csv("/content/drive/MyDrive/train_dataset2.csv")


In [29]:
df["CODE_GENDER"] =  df["CODE_GENDER"].replace(['F','M'],[0,1])
df["FLAG_OWN_CAR"] = df["FLAG_OWN_CAR"].replace(["Y","N"],[1,0])
df["FLAG_OWN_REALTY"] = df["FLAG_OWN_REALTY"].replace(["Y","N"],[1,0])

df["STATUS"] =  df["STATUS"].replace(['X','C', '0', '1', '2', '3', '4', '5'],[0,1,2,3,4,5,6,7])

In [30]:
df.drop('ID', axis=1, inplace=True)

In [31]:
names = df.keys()
print(names)

Index(['CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN',
       'AMT_INCOME_TOTAL', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE',
       'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'FLAG_WORK_PHONE',
       'FLAG_PHONE', 'FLAG_EMAIL', 'OCCUPATION_TYPE', 'CNT_FAM_MEMBERS',
       'BEGIN_MONTH', 'AGES', 'WORKING_YEAR', 'STATUS'],
      dtype='object')


In [32]:
types = df.dtypes
print(types)

CODE_GENDER              int64
FLAG_OWN_CAR             int64
FLAG_OWN_REALTY          int64
CNT_CHILDREN            object
AMT_INCOME_TOTAL       float64
NAME_INCOME_TYPE        object
NAME_EDUCATION_TYPE     object
NAME_FAMILY_STATUS      object
NAME_HOUSING_TYPE       object
FLAG_WORK_PHONE          int64
FLAG_PHONE               int64
FLAG_EMAIL               int64
OCCUPATION_TYPE         object
CNT_FAM_MEMBERS         object
BEGIN_MONTH            float64
AGES                     int64
WORKING_YEAR             int64
STATUS                   int64
dtype: object


In [33]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for i in range(len(types)):
    if types[i] == 'object':
        # Chuyển đổi cột thành chuỗi nếu nó không phải kiểu chuỗi
        df[names[i]] = df[names[i]].astype(str)

        le.fit(df[names[i]])
        df[names[i]] = le.transform(df[names[i]])

In [34]:
data = np.array(df.values)
data

array([[ 0.,  1.,  0., ..., 48.,  4.,  0.],
       [ 0.,  0.,  1., ..., 33., 10.,  0.],
       [ 0.,  0.,  1., ..., 63.,  0.,  2.],
       ...,
       [ 0.,  0.,  1., ..., 33.,  0.,  2.],
       [ 0.,  0.,  1., ..., 67.,  0.,  2.],
       [ 0.,  1.,  1., ..., 41., 14.,  0.]])

In [35]:
X = data[:,:-1]
y = data[:,-1]

In [36]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print('Train:')
print(X_train.shape)
print(y_train.shape)
print('Test:')
print(X_test.shape)
print(y_test.shape)

Train:
(23332, 17)
(23332,)
Test:
(5834, 17)
(5834,)


In [37]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [38]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train_scaled,y_train)


clf_pred = clf.predict(X_test_scaled)

print('DT')
print('Accuracy Score is {:.5}'.format(accuracy_score(y_test, clf_pred)))
print(classification_report(y_test, clf_pred))
print(confusion_matrix(y_test, clf_pred))

DT
Accuracy Score is 0.48457
              precision    recall  f1-score   support

         0.0       0.34      0.37      0.36      1508
         1.0       0.63      0.59      0.61      2965
         2.0       0.38      0.38      0.38      1282
         3.0       0.12      0.12      0.12        58
         4.0       0.33      0.50      0.40         2
         5.0       0.00      0.00      0.00         2
         6.0       0.00      0.00      0.00         1
         7.0       0.20      0.12      0.15        16

    accuracy                           0.48      5834
   macro avg       0.25      0.26      0.25      5834
weighted avg       0.49      0.48      0.49      5834

[[ 565  596  331   12    0    0    0    4]
 [ 738 1763  444   14    0    2    0    4]
 [ 339  428  489   23    2    0    1    0]
 [  12   19   20    7    0    0    0    0]
 [   0    0    1    0    1    0    0    0]
 [   1    1    0    0    0    0    0    0]
 [   0    0    1    0    0    0    0    0]
 [   7    4    3   

In [39]:
joblib.dump({'model': clf, 'label_encoder': le, 'StandardScaler':scaler}, 'dt.joblib')

['dt.joblib']

In [40]:
# Initialize the Logistic Regression model
logistic_model = LogisticRegression()

# Train the model
logistic_model.fit(X_train_scaled, y_train)



logistic_pred = logistic_model.predict(X_test_scaled)

# Evaluate the model
print('Accuracy Score is {:.5}'.format(accuracy_score(y_test, logistic_pred)))
print(classification_report(y_test, logistic_pred))
print(confusion_matrix(y_test, logistic_pred))

Accuracy Score is 0.56668
              precision    recall  f1-score   support

         0.0       0.22      0.00      0.00      1508
         1.0       0.60      0.87      0.71      2965
         2.0       0.47      0.57      0.51      1282
         3.0       0.00      0.00      0.00        58
         4.0       0.00      0.00      0.00         2
         5.0       0.00      0.00      0.00         2
         6.0       0.00      0.00      0.00         1
         7.0       0.00      0.00      0.00        16

    accuracy                           0.57      5834
   macro avg       0.16      0.18      0.15      5834
weighted avg       0.47      0.57      0.48      5834

[[   2 1099  407    0    0    0    0    0]
 [   6 2571  388    0    0    0    0    0]
 [   1  548  733    0    0    0    0    0]
 [   0   21   37    0    0    0    0    0]
 [   0    0    2    0    0    0    0    0]
 [   0    1    1    0    0    0    0    0]
 [   0    0    1    0    0    0    0    0]
 [   0   13    3    0 

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels wit

In [41]:
joblib.dump({'model': logistic_model, 'label_encoder': le, 'StandardScaler':scaler}, 'logistic.joblib')

['logistic.joblib']

In [42]:

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import numpy as np
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

In [43]:
model = make_pipeline(StandardScaler(), KNeighborsClassifier())


param_grid = {'kneighborsclassifier__n_neighbors': np.arange(1, 31)}


grid_search = GridSearchCV(model, param_grid, cv=5, scoring='accuracy')


grid_search.fit(X_train, y_train)


print("Best Parameters:", grid_search.best_params_)
print("Best Cross-Validated Accuracy:", grid_search.best_score_)


test_accuracy = grid_search.score(X_test, y_test)
print("Test Set Accuracy:", test_accuracy)

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:737: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(


Best Parameters: {'kneighborsclassifier__n_neighbors': 1}
Best Cross-Validated Accuracy: 0.5328730208573369
Test Set Accuracy: 0.5478231059307508


In [44]:
k = 1
knn = KNeighborsClassifier(n_neighbors=k,weights='distance')
knn.fit(X_train_scaled, y_train)

KNeighborsClassifier(n_neighbors=1, weights='distance')

In [45]:
y_pred = knn.predict(X_test_scaled)
accuracy = accuracy_score(y_test, y_pred)
print(f"Độ chính xác: {accuracy}")
print(classification_report(y_test, y_pred))

Độ chính xác: 0.5478231059307508
              precision    recall  f1-score   support

         0.0       0.43      0.44      0.44      1508
         1.0       0.66      0.66      0.66      2965
         2.0       0.44      0.43      0.44      1282
         3.0       0.18      0.12      0.14        58
         4.0       0.33      0.50      0.40         2
         5.0       0.00      0.00      0.00         2
         6.0       0.00      0.00      0.00         1
         7.0       0.25      0.19      0.21        16

    accuracy                           0.55      5834
   macro avg       0.29      0.29      0.29      5834
weighted avg       0.55      0.55      0.55      5834



In [46]:
joblib.dump({'model': knn, 'label_encoder': le, 'StandardScaler':scaler}, 'knn_model.joblib')

['knn_model.joblib']

In [47]:
'''
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score


param_grid = {'kernel': ['linear', 'poly', 'rbf', 'sigmoid'],
              'C': [0.1, 1, 10],
              'gamma': ['scale', 'auto', 0.1, 1]}
svm_model = SVC()
grid_search = GridSearchCV(svm_model, param_grid, cv=2, scoring='accuracy')
grid_search.fit(X_train_scaled, y_train)

best_kernel = grid_search.best_params_['kernel']
best_C = grid_search.best_params_['C']
best_gamma = grid_search.best_params_['gamma']


best_svm_model = SVC(kernel=best_kernel, C=best_C, gamma=best_gamma)


best_svm_model.fit(X_train_scaled, y_train)


y_pred = best_svm_model.predict(X_test_scaled)
accuracy = accuracy_score(y_test, y_pred)

print(f'The best kernel is {best_kernel} with C={best_C} and gamma={best_gamma}')
print(f'Accuracy on the test set: {accuracy}')
'''

"\nfrom sklearn.model_selection import train_test_split, GridSearchCV\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.svm import SVC\nfrom sklearn.metrics import accuracy_score\n\n\nparam_grid = {'kernel': ['linear', 'poly', 'rbf', 'sigmoid'],\n              'C': [0.1, 1, 10],\n              'gamma': ['scale', 'auto', 0.1, 1]}\nsvm_model = SVC()\ngrid_search = GridSearchCV(svm_model, param_grid, cv=2, scoring='accuracy')\ngrid_search.fit(X_train_scaled, y_train)\n\nbest_kernel = grid_search.best_params_['kernel']\nbest_C = grid_search.best_params_['C']\nbest_gamma = grid_search.best_params_['gamma']\n\n\nbest_svm_model = SVC(kernel=best_kernel, C=best_C, gamma=best_gamma)\n\n\nbest_svm_model.fit(X_train_scaled, y_train)\n\n\ny_pred = best_svm_model.predict(X_test_scaled)\naccuracy = accuracy_score(y_test, y_pred)\n\nprint(f'The best kernel is {best_kernel} with C={best_C} and gamma={best_gamma}')\nprint(f'Accuracy on the test set: {accuracy}')\n"

In [48]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report




svm_model = SVC(kernel='linear', C=0.1, gamma='scale')


svm_model.fit(X_train_scaled, y_train)


y_pred = svm_model.predict(X_test_scaled)


accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print(report)

Accuracy: 0.5569077819677751
              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00      1508
         1.0       0.61      0.83      0.70      2965
         2.0       0.44      0.62      0.51      1282
         3.0       0.00      0.00      0.00        58
         4.0       0.00      0.00      0.00         2
         5.0       0.00      0.00      0.00         2
         6.0       0.00      0.00      0.00         1
         7.0       0.00      0.00      0.00        16

    accuracy                           0.56      5834
   macro avg       0.13      0.18      0.15      5834
weighted avg       0.41      0.56      0.47      5834



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [49]:
joblib.dump({'model': svm_model, 'label_encoder': le, 'StandardScaler':scaler}, 'svm_model.joblib')

['svm_model.joblib']