In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from joblib import dump
import joblib

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv("train_dataset2.csv")


In [3]:
df["CODE_GENDER"] =  df["CODE_GENDER"].replace(['F','M'],[0,1])
df["FLAG_OWN_CAR"] = df["FLAG_OWN_CAR"].replace(["Y","N"],[1,0])
df["FLAG_OWN_REALTY"] = df["FLAG_OWN_REALTY"].replace(["Y","N"],[1,0])

df["STATUS"] =  df["STATUS"].replace(['X','C', '0', '1', '2', '3', '4', '5'],[0,1,2,3,4,5,6,7])

In [4]:
df.drop('ID', axis=1, inplace=True)

In [5]:
names = df.keys()
print(names)

Index(['CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN',
       'AMT_INCOME_TOTAL', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE',
       'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'FLAG_WORK_PHONE',
       'FLAG_PHONE', 'FLAG_EMAIL', 'OCCUPATION_TYPE', 'CNT_FAM_MEMBERS',
       'BEGIN_MONTH', 'AGES', 'WORKING_YEAR', 'STATUS'],
      dtype='object')


In [6]:
types = df.dtypes
print(types)

CODE_GENDER              int64
FLAG_OWN_CAR             int64
FLAG_OWN_REALTY          int64
CNT_CHILDREN            object
AMT_INCOME_TOTAL       float64
NAME_INCOME_TYPE        object
NAME_EDUCATION_TYPE     object
NAME_FAMILY_STATUS      object
NAME_HOUSING_TYPE       object
FLAG_WORK_PHONE          int64
FLAG_PHONE               int64
FLAG_EMAIL               int64
OCCUPATION_TYPE         object
CNT_FAM_MEMBERS         object
BEGIN_MONTH            float64
AGES                     int64
WORKING_YEAR             int64
STATUS                   int64
dtype: object


In [7]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for i in range(len(types)):
    if types[i] == 'object':
        # Chuyển đổi cột thành chuỗi nếu nó không phải kiểu chuỗi
        df[names[i]] = df[names[i]].astype(str)

        le.fit(df[names[i]])
        df[names[i]] = le.transform(df[names[i]])

In [8]:
data = np.array(df.values)
data

array([[ 0.,  1.,  0., ..., 48.,  4.,  0.],
       [ 0.,  0.,  1., ..., 33., 10.,  0.],
       [ 0.,  0.,  1., ..., 63.,  0.,  2.],
       ...,
       [ 0.,  0.,  1., ..., 33.,  0.,  2.],
       [ 0.,  0.,  1., ..., 67.,  0.,  2.],
       [ 0.,  1.,  1., ..., 41., 14.,  0.]])

In [9]:
X = data[:,:-1]
y = data[:,-1]

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print('Train:')
print(X_train.shape)
print(y_train.shape)
print('Test:')
print(X_test.shape)
print(y_test.shape)

Train:
(23332, 17)
(23332,)
Test:
(5834, 17)
(5834,)


In [11]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [12]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train_scaled,y_train)


clf_pred = clf.predict(X_test_scaled)

print('DT')
print('Accuracy Score is {:.5}'.format(accuracy_score(y_test, clf_pred)))
print(classification_report(y_test, clf_pred))
print(confusion_matrix(y_test, clf_pred))

DT
Accuracy Score is 0.48817
              precision    recall  f1-score   support

         0.0       0.34      0.37      0.36      1508
         1.0       0.63      0.60      0.61      2965
         2.0       0.38      0.40      0.39      1282
         3.0       0.12      0.12      0.12        58
         4.0       0.50      0.50      0.50         2
         5.0       0.00      0.00      0.00         2
         6.0       0.00      0.00      0.00         1
         7.0       0.22      0.12      0.16        16

    accuracy                           0.49      5834
   macro avg       0.28      0.26      0.27      5834
weighted avg       0.49      0.49      0.49      5834

[[ 555  594  342   14    0    0    0    3]
 [ 723 1776  444   15    0    2    1    4]
 [ 316  436  507   21    1    0    1    0]
 [  12   21   18    7    0    0    0    0]
 [   0    0    1    0    1    0    0    0]
 [   1    0    1    0    0    0    0    0]
 [   0    0    1    0    0    0    0    0]
 [   8    3    3   

In [13]:
joblib.dump({'model': clf, 'label_encoder': le, 'StandardScaler':scaler}, 'dt1.joblib')

['dt1.joblib']

In [14]:
# Initialize the Logistic Regression model
logistic_model = LogisticRegression()

# Train the model
logistic_model.fit(X_train_scaled, y_train)



logistic_pred = logistic_model.predict(X_test_scaled)

# Evaluate the model
print('Accuracy Score is {:.5}'.format(accuracy_score(y_test, logistic_pred)))
print(classification_report(y_test, logistic_pred))
print(confusion_matrix(y_test, logistic_pred))

Accuracy Score is 0.56668
              precision    recall  f1-score   support

         0.0       0.22      0.00      0.00      1508
         1.0       0.60      0.87      0.71      2965
         2.0       0.47      0.57      0.51      1282
         3.0       0.00      0.00      0.00        58
         4.0       0.00      0.00      0.00         2
         5.0       0.00      0.00      0.00         2
         6.0       0.00      0.00      0.00         1
         7.0       0.00      0.00      0.00        16

    accuracy                           0.57      5834
   macro avg       0.16      0.18      0.15      5834
weighted avg       0.47      0.57      0.48      5834

[[   2 1099  407    0    0    0    0    0]
 [   6 2571  388    0    0    0    0    0]
 [   1  548  733    0    0    0    0    0]
 [   0   21   37    0    0    0    0    0]
 [   0    0    2    0    0    0    0    0]
 [   0    1    1    0    0    0    0    0]
 [   0    0    1    0    0    0    0    0]
 [   0   13    3    0 

C:\Users\thanh\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\thanh\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\thanh\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in l

In [15]:
joblib.dump({'model': logistic_model, 'label_encoder': le, 'StandardScaler':scaler}, 'logistic.joblib')

['logistic.joblib']

In [16]:
import joblib
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import numpy as np
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

In [17]:
# model = make_pipeline(StandardScaler(), KNeighborsClassifier())


# param_grid = {'kneighborsclassifier__n_neighbors': np.arange(1, 31)}


# grid_search = GridSearchCV(model, param_grid, cv=5, scoring='accuracy')


# grid_search.fit(X_train, y_train)


# print("Best Parameters:", grid_search.best_params_)
# print("Best Cross-Validated Accuracy:", grid_search.best_score_)


# test_accuracy = grid_search.score(X_test, y_test)
# print("Test Set Accuracy:", test_accuracy)

In [18]:
k = 20
knn = KNeighborsClassifier(n_neighbors=k,weights='distance')
knn.fit(X_train_scaled, y_train)

KNeighborsClassifier(n_neighbors=20, weights='distance')

In [19]:
y_pred = knn.predict(X_test_scaled)
accuracy = accuracy_score(y_test, y_pred)
print(f"Độ chính xác: {accuracy}")
print(classification_report(y_test, y_pred))

AttributeError: 'NoneType' object has no attribute 'split'

In [ ]:
joblib.dump({'model': knn, 'label_encoder': le, 'StandardScaler':scaler}, 'knn_model.joblib')

In [ ]:
# from sklearn.model_selection import train_test_split, GridSearchCV
# from sklearn.preprocessing import StandardScaler
# from sklearn.svm import SVC
# from sklearn.metrics import accuracy_score


# param_grid = {'kernel': ['linear', 'poly', 'rbf', 'sigmoid'],
#               'C': [0.1, 1, 10],
#               'gamma': ['scale', 'auto', 0.1, 1]}
# svm_model = SVC()
# grid_search = GridSearchCV(svm_model, param_grid, cv=2, scoring='accuracy')
# grid_search.fit(X_train_scaled, y_train)

# best_kernel = grid_search.best_params_['kernel']
# best_C = grid_search.best_params_['C']
# best_gamma = grid_search.best_params_['gamma']


# best_svm_model = SVC(kernel=best_kernel, C=best_C, gamma=best_gamma)


# best_svm_model.fit(X_train_scaled, y_train)


# y_pred = best_svm_model.predict(X_test_scaled)
# accuracy = accuracy_score(y_test, y_pred)

# print(f'The best kernel is {best_kernel} with C={best_C} and gamma={best_gamma}')
# print(f'Accuracy on the test set: {accuracy}')

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report




svm_model = SVC(kernel='linear', C=0.1, gamma='scale')


svm_model.fit(X_train_scaled, y_train)


y_pred = svm_model.predict(X_test_scaled)


accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print(report)

In [ ]:
joblib.dump({'model': svm_model, 'label_encoder': le, 'StandardScaler':scaler}, 'svm_model.joblib')

In [ ]:
#from cmd
import sklearn
sklearn_version = sklearn.__version__

print(sklearn_version)

In [21]:
X_test_scaled is not None


True